const COMPANION_QUESTION_TREE = {
    "q0": { text: "1", next: {'0': 'q1', '1': 'q1', '2': 'q0_a', '3': 'q0_a', '4': 'q0_a', 'default': 'q1'} },
    "q0_a": { text: "What specific triggers consistently lead to this high level of severity for you?", next: {'default': 'q1'} },
    "q1": { text: "I feel slowed down or weighed down much of the day.", next: {'0': 'q2', '1': 'q2', '2': 'q1_a', '3': 'q1_a', '4': 'q1_a', 'default': 'q2'} },
    "q1_a": { text: "What daily activities are most impacted when you feel slowed down or weighed down?", next: {'default': 'q2'} },
    "q2": { text: "My day feels harder to start than it should.", next: {'0': 'q3', '1': 'q3', '2': 'q2_a', '3': 'q2_a', '4': 'q2_a', 'default': 'q3'} },
    "q2_a": { text: "What specific factors make starting your day particularly challenging?", next: {'default': 'q3'} },
    "q3": { text: "My depressive state is reducing how much life I can carry.", next: {'0': 'q4', '1': 'q4', '2': 'q3_a', '3': 'q3_a', '4': 'q3_a', 'default': 'q4'} },
    "q3_a": { text: "What specific activities or responsibilities are most impacted by your depressive state?", next: {'default': 'q4'} },
    "q4": { text: "Basic tasks feel disproportionately expensive.", next: {'0': 'q5', '1': 'q5', '2': 'q4_a', '3': 'q4_a', '4': 'q4_a', 'default': 'q5'} },
    "q4_a": { text: "What specific tasks trigger this feeling of disproportionate expense most frequently?", next: {'default': 'q5'} },
    "q5": { text: "I lose large amounts of time to drifting, freezing, or shutting down.", next: {'0': 'q6', '1': 'q6', '2': 'q5_a', '3': 'q5_a', '4': 'q5_a', 'default': 'q6'} },
    "q5_a": { text: "What triggers the episodes of drifting, freezing, or shutting down for you?", next: {'default': 'q6'} },
    "q6": { text: "My functioning is worse than my mood alone would suggest.", next: {'0': 'q7', '1': 'q7', '2': 'q6_a', '3': 'q6_a', '4': 'q6_a', 'default': 'q7'} },
    "q6_a": { text: "What specific situations worsen your functioning despite a stable mood?", next: {'default': 'q7'} },
    "q7": { text: "I feel less able to handle ordinary stress than I used to.", next: {'0': 'q8', '1': 'q8', '2': 'q7_a', '3': 'q7_a', '4': 'q7_a', 'default': 'q8'} },
    "q7_a": { text: "What specific stressors have become more challenging for you recently?", next: {'default': 'q8'} },
    "q8": { text: "I am letting important tasks pile up because they feel too heavy.", next: {'0': 'q9', '1': 'q9', '2': 'q8_a', '3': 'q8_a', '4': 'q8_a', 'default': 'q9'} },
    "q8_a": { text: "What specific barriers are preventing you from starting these important tasks?", next: {'default': 'q9'} },
    "q9": { text: "My depression is damaging work, school, or household functioning.", next: {'0': 'q10', '1': 'q10', '2': 'q9_a', '3': 'q9_a', '4': 'q9_a', 'default': 'q10'} },
    "q9_a": { text: "What specific tasks or responsibilities are most affected by your depression?", next: {'default': 'q10'} },
    "q10": { text: "I am having trouble maintaining hygiene or basic self-care.", next: {'0': 'q11', '1': 'q11', '2': 'q10_a', '3': 'q10_a', '4': 'q10_a', 'default': 'q11'} },
    "q10_a": { text: "What specific barriers are preventing you from maintaining your hygiene or self-care?", next: {'default': 'q11'} },
    "q11": { text: "My appetite or eating pattern has become less reliable.", next: {'0': 'q12', '1': 'q12', '2': 'q11_a', '3': 'q11_a', '4': 'q11_a', 'default': 'q12'} },
    "q11_a": { text: "What specific factors trigger changes in your appetite or eating patterns?", next: {'default': 'q12'} },
    "q12": { text: "I feel disconnected from pleasure, interest, or reward.", next: {'0': 'q13', '1': 'q13', '2': 'q12_a', '3': 'q12_a', '4': 'q12_a', 'default': 'q13'} },
    "q12_a": { text: "What specific situations trigger your sense of disconnection from pleasure or interest?", next: {'default': 'q13'} },
    "q13": { text: "I feel like my range of action has narrowed.", next: {'0': 'q14', '1': 'q14', '2': 'q13_a', '3': 'q13_a', '4': 'q13_a', 'default': 'q14'} },
    "q13_a": { text: "What specific activities do you feel have become restricted or inaccessible recently?", next: {'default': 'q14'} },
    "q14": { text: "Small setbacks hit me harder than they should.", next: {'0': 'q15', '1': 'q15', '2': 'q14_a', '3': 'q14_a', '4': 'q14_a', 'default': 'q15'} },
    "q14_a": { text: "What specific thoughts arise immediately after experiencing a small setback?", next: {'default': 'q15'} },
    "q15": { text: "My current functioning feels fragile or inconsistent.", next: {'0': 'q16', '1': 'q16', '2': 'q15_a', '3': 'q15_a', '4': 'q15_a', 'default': 'q16'} },
    "q15_a": { text: "What specific events or changes trigger fluctuations in your functioning?", next: {'default': 'q16'} },
    "q16": { text: "I feel sad, flat, empty, or emotionally blunted.", next: {'0': 'q17', '1': 'q17', '2': 'q16_a', '3': 'q16_a', '4': 'q16_a', 'default': 'q17'} },
    "q16_a": { text: "What recent changes or stressors might have contributed to these feelings?", next: {'default': 'q17'} },
    "q17": { text: "I get less pleasure from things that used to help.", next: {'0': 'q18', '1': 'q18', '2': 'q17_a', '3': 'q17_a', '4': 'q17_a', 'default': 'q18'} },
    "q17_a": { text: "What specific activities have lost their appeal and when did this change start?", next: {'default': 'q18'} },
    "q18": { text: "Positive events have less impact on me than they used to.", next: {'0': 'q19', '1': 'q19', '2': 'q18_a', '3': 'q18_a', '4': 'q18_a', 'default': 'q19'} },
    "q18_a": { text: "What recent changes in your life might be affecting your response to positive events?", next: {'default': 'q19'} },
    "q19": { text: "I have trouble imagining enjoying the future.", next: {'0': 'q20', '1': 'q20', '2': 'q19_a', '3': 'q19_a', '4': 'q19_a', 'default': 'q20'} },
    "q19_a": { text: "What specific future events feel most difficult for you to envision enjoying?", next: {'default': 'q20'} },
    "q20": { text: "I feel hopeless about meaningful change.", next: {'0': 'q21', '1': 'q21', '2': 'q20_a', '3': 'q20_a', '4': 'q20_a', 'default': 'q21'} },
    "q20_a": { text: "What specific past experiences contribute most to your sense of hopelessness about change?", next: {'default': 'q21'} },
    "q21": { text: "I feel emotionally numb more than simply tired.", next: {'0': 'q22', '1': 'q22', '2': 'q21_a', '3': 'q21_a', '4': 'q21_a', 'default': 'q22'} },
    "q21_a": { text: "What situations trigger your emotional numbness most frequently?", next: {'default': 'q22'} },
    "q22": { text: "I feel grief-like heaviness without clear relief.", next: {'0': 'q23', '1': 'q23', '2': 'q22_a', '3': 'q22_a', '4': 'q22_a', 'default': 'q23'} },
    "q22_a": { text: "What triggers or situations intensify your experience of grief-like heaviness?", next: {'default': 'q23'} },
    "q23": { text: "I feel irritable or more easily frustrated.", next: {'0': 'q24', '1': 'q24', '2': 'q23_a', '3': 'q23_a', '4': 'q23_a', 'default': 'q24'} },
    "q23_a": { text: "What specific situations or triggers do you notice increase your irritability or frustration?", next: {'default': 'q24'} },
    "q24": { text: "My mood drops sharply with small disappointments.", next: {'0': 'q25', '1': 'q25', '2': 'q24_a', '3': 'q24_a', '4': 'q24_a', 'default': 'q25'} },
    "q24_a": { text: "What specific thoughts or beliefs trigger your mood drop during these disappointments?", next: {'default': 'q25'} },
    "q25": { text: "I feel like life has lost some of its color.", next: {'0': 'q26', '1': 'q26', '2': 'q25_a', '3': 'q25_a', '4': 'q25_a', 'default': 'q26'} },
    "q25_a": { text: "What specific changes or events preceded the feeling that life lost its color?", next: {'default': 'q26'} },
    "q26": { text: "I feel guilty or defective much of the time.", next: {'0': 'q27', '1': 'q27', '2': 'q26_a', '3': 'q26_a', '4': 'q26_a', 'default': 'q27'} },
    "q26_a": { text: "What specific experiences or thoughts trigger your feelings of guilt or defectiveness?", next: {'default': 'q27'} },
    "q27": { text: "I feel ashamed of struggling this much.", next: {'0': 'q28', '1': 'q28', '2': 'q27_a', '3': 'q27_a', '4': 'q27_a', 'default': 'q28'} },
    "q27_a": { text: "What specific expectations do you feel you're not meeting that's causing your shame?", next: {'default': 'q28'} },
    "q28": { text: "I feel like effort probably will not pay off.", next: {'0': 'q29', '1': 'q29', '2': 'q28_a', '3': 'q28_a', '4': 'q28_a', 'default': 'q29'} },
    "q28_a": { text: "What specific past experiences lead you to believe effort won't pay off?", next: {'default': 'q29'} },
    "q29": { text: "I feel stuck in the same state with little movement.", next: {'0': 'q30', '1': 'q30', '2': 'q29_a', '3': 'q29_a', '4': 'q29_a', 'default': 'q30'} },
    "q29_a": { text: "What specific situations or triggers do you associate with feeling stuck or immobilized?", next: {'default': 'q30'} },
    "q30": { text: "I feel disconnected from wanting things.", next: {'0': 'q31', '1': 'q31', '2': 'q30_a', '3': 'q30_a', '4': 'q30_a', 'default': 'q31'} },
    "q30_a": { text: "What recent changes in your life might have influenced your sense of desire?", next: {'default': 'q31'} },
    "q31": { text: "My thinking becomes darker or harsher when I am low.", next: {'0': 'q32', '1': 'q32', '2': 'q31_a', '3': 'q31_a', '4': 'q31_a', 'default': 'q32'} },
    "q31_a": { text: "What specific thoughts or events trigger this darkening or harshness in your thinking?", next: {'default': 'q32'} },
    "q32": { text: "I mistake depressed thoughts for objective truth.", next: {'0': 'q33', '1': 'q33', '2': 'q32_a', '3': 'q32_a', '4': 'q32_a', 'default': 'q33'} },
    "q32_a": { text: "What specific thoughts do you frequently misinterpret as factual truths?", next: {'default': 'q33'} },
    "q33": { text: "I replay problems without getting clearer or closer to action.", next: {'0': 'q34', '1': 'q34', '2': 'q33_a', '3': 'q33_a', '4': 'q33_a', 'default': 'q34'} },
    "q33_a": { text: "What factors trigger or exacerbate your tendency to ruminate on problems?", next: {'default': 'q34'} },
    "q34": { text: "I build cases against myself in my own head.", next: {'0': 'q35', '1': 'q35', '2': 'q34_a', '3': 'q34_a', '4': 'q34_a', 'default': 'q35'} },
    "q34_a": { text: "What triggers the initial thoughts that lead to building cases against yourself?", next: {'default': 'q35'} },
    "q35": { text: "I focus more on failure than on contrary evidence.", next: {'0': 'q36', '1': 'q36', '2': 'q35_a', '3': 'q35_a', '4': 'q35_a', 'default': 'q36'} },
    "q35_a": { text: "What specific situations trigger your tendency to focus on perceived failures?", next: {'default': 'q36'} },
    "q36": { text: "I have trouble making ordinary decisions.", next: {'0': 'q37', '1': 'q37', '2': 'q36_a', '3': 'q36_a', '4': 'q36_a', 'default': 'q37'} },
    "q36_a": { text: "What specific factors make decision-making challenging for you in daily situations?", next: {'default': 'q37'} },
    "q37": { text: "My concentration is worse than normal.", next: {'0': 'q38', '1': 'q38', '2': 'q37_a', '3': 'q37_a', '4': 'q37_a', 'default': 'q38'} },
    "q37_a": { text: "What specific activities or times of day worsen your concentration difficulties?", next: {'default': 'q38'} },
    "q38": { text: "I feel mentally slowed or foggy.", next: {'0': 'q39', '1': 'q39', '2': 'q38_a', '3': 'q38_a', '4': 'q38_a', 'default': 'q39'} },
    "q38_a": { text: "What situations or activities worsen your feelings of mental slowness or fog?", next: {'default': 'q39'} },
    "q39": { text: "I expect bad outcomes before I try.", next: {'0': 'q40', '1': 'q40', '2': 'q39_a', '3': 'q39_a', '4': 'q39_a', 'default': 'q40'} },
    "q39_a": { text: "What past experiences contribute to your expectation of negative outcomes?", next: {'default': 'q40'} },
    "q40": { text: "I interpret delays or neutral events as proof that I am failing.", next: {'0': 'q41', '1': 'q41', '2': 'q40_a', '3': 'q40_a', '4': 'q40_a', 'default': 'q41'} },
    "q40_a": { text: "What past experiences contribute to interpreting delays as personal failures?", next: {'default': 'q41'} },
    "q41": { text: "I have trouble holding perspective once shame gets high.", next: {'0': 'q42', '1': 'q42', '2': 'q41_a', '3': 'q41_a', '4': 'q41_a', 'default': 'q42'} },
    "q41_a": { text: "What specific thoughts or situations trigger heightened shame for you?", next: {'default': 'q42'} },
    "q42": { text: "My mind erases evidence that I can handle things.", next: {'0': 'q43', '1': 'q43', '2': 'q42_a', '3': 'q42_a', '4': 'q42_a', 'default': 'q43'} },
    "q42_a": { text: "What specific situations trigger your mind to erase evidence of your capabilities?", next: {'default': 'q43'} },
    "q43": { text: "I compare myself to others in ways that make me collapse further.", next: {'0': 'q44', '1': 'q44', '2': 'q43_a', '3': 'q43_a', '4': 'q43_a', 'default': 'q44'} },
    "q43_a": { text: "What specific situations trigger these comparisons leading to emotional collapse?", next: {'default': 'q44'} },
    "q44": { text: "I struggle to separate a bad state from my whole identity.", next: {'0': 'q45', '1': 'q45', '2': 'q44_a', '3': 'q44_a', '4': 'q44_a', 'default': 'q45'} },
    "q44_a": { text: "What specific thoughts or beliefs reinforce your identification with negative states?", next: {'default': 'q45'} },
    "q45": { text: "I have trouble seeing temporary conditions as temporary.", next: {'0': 'q46', '1': 'q46', '2': 'q45_a', '3': 'q45_a', '4': 'q45_a', 'default': 'q46'} },
    "q45_a": { text: "What influences your perception that temporary conditions might become permanent?", next: {'default': 'q46'} },
    "q46": { text: "My sleep schedule is drifting later or becoming irregular.", next: {'0': 'q47', '1': 'q47', '2': 'q46_a', '3': 'q46_a', '4': 'q46_a', 'default': 'q47'} },
    "q46_a": { text: "What changes in your daily routine might be contributing to your irregular sleep patterns?", next: {'default': 'q47'} },
    "q47": { text: "I have trouble falling asleep when I intend to.", next: {'0': 'q48', '1': 'q48', '2': 'q47_a', '3': 'q47_a', '4': 'q47_a', 'default': 'q48'} },
    "q47_a": { text: "What specific thoughts or activities prevent you from falling asleep at your intended time?", next: {'default': 'q48'} },
    "q48": { text: "I wake often or sleep lightly.", next: {'0': 'q49', '1': 'q49', '2': 'q48_a', '3': 'q48_a', '4': 'q48_a', 'default': 'q49'} },
    "q48_a": { text: "What specific thoughts or events trigger your nighttime awakenings?", next: {'default': 'q49'} },
    "q49": { text: "I wake without feeling restored.", next: {'0': 'q50', '1': 'q50', '2': 'q49_a', '3': 'q49_a', '4': 'q49_a', 'default': 'q50'} },
    "q49_a": { text: "What patterns or habits affect your sleep quality and duration?", next: {'default': 'q50'} },
    "q50": { text: "I oversleep or stay in bed longer than intended.", next: {'0': 'q51', '1': 'q51', '2': 'q50_a', '3': 'q50_a', '4': 'q50_a', 'default': 'q51'} },
    "q50_a": { text: "What factors contribute to your decision to remain in bed longer than planned?", next: {'default': 'q51'} },
    "q51": { text: "My wake time changes a lot from day to day.", next: {'0': 'q52', '1': 'q52', '2': 'q51_a', '3': 'q51_a', '4': 'q51_a', 'default': 'q52'} },
    "q51_a": { text: "What factors contribute to the variability in your daily wake time?", next: {'default': 'q52'} },
    "q52": { text: "Morning light or daylight exposure is inconsistent.", next: {'0': 'q53', '1': 'q53', '2': 'q52_a', '3': 'q52_a', '4': 'q52_a', 'default': 'q53'} },
    "q52_a": { text: "What factors prevent consistent morning light exposure in your daily routine?", next: {'default': 'q53'} },
    "q53": { text: "Low sleep quality makes everything else worse.", next: {'0': 'q54', '1': 'q54', '2': 'q53_a', '3': 'q53_a', '4': 'q53_a', 'default': 'q54'} },
    "q53_a": { text: "What specific aspects of your daily routine are most disrupted by poor sleep quality?", next: {'default': 'q54'} },
    "q54": { text: "I use sleep, lying down, or hiding in bed to escape the day.", next: {'0': 'q55', '1': 'q55', '2': 'q54_a', '3': 'q54_a', '4': 'q54_a', 'default': 'q55'} },
    "q54_a": { text: "What specific situations trigger your urge to escape by sleeping or hiding in bed?", next: {'default': 'q55'} },
    "q55": { text: "My evenings get taken over by passive numbing or scrolling.", next: {'0': 'q56', '1': 'q56', '2': 'q55_a', '3': 'q55_a', '4': 'q55_a', 'default': 'q56'} },
    "q55_a": { text: "What triggers your urge to engage in passive numbing or scrolling in evenings?", next: {'default': 'q56'} },
    "q56": { text: "My sleep pattern makes mornings feel unwinnable.", next: {'0': 'q57', '1': 'q57', '2': 'q56_a', '3': 'q56_a', '4': 'q56_a', 'default': 'q57'} },
    "q56_a": { text: "What specific sleep disruptions contribute most to your difficult mornings?", next: {'default': 'q57'} },
    "q57": { text: "I delay starting the day even after waking.", next: {'0': 'q58', '1': 'q58', '2': 'q57_a', '3': 'q57_a', '4': 'q57_a', 'default': 'q58'} },
    "q57_a": { text: "What thoughts or activities contribute to delaying your start in the morning?", next: {'default': 'q58'} },
    "q58": { text: "My energy rhythm feels badly timed or unstable.", next: {'0': 'q59', '1': 'q59', '2': 'q58_a', '3': 'q58_a', '4': 'q58_a', 'default': 'q59'} },
    "q58_a": { text: "What factors or events typically disrupt your energy rhythm throughout the day?", next: {'default': 'q59'} },
    "q59": { text: "I have trouble protecting a realistic wind-down window.", next: {'0': 'q60', '1': 'q60', '2': 'q59_a', '3': 'q59_a', '4': 'q59_a', 'default': 'q60'} },
    "q59_a": { text: "What specific activities or thoughts disrupt your wind-down process before sleep?", next: {'default': 'q60'} },
    "q60": { text: "Sleep disruption is one of the main engines of my depression right now.", next: {'0': 'q61', '1': 'q61', '2': 'q60_a', '3': 'q60_a', '4': 'q60_a', 'default': 'q61'} },
    "q60_a": { text: "What specific sleep disruptions are most impacting your mood and daily functioning?", next: {'default': 'q61'} },
    "q61": { text: "My energy is low most days.", next: {'0': 'q62', '1': 'q62', '2': 'q61_a', '3': 'q61_a', '4': 'q61_a', 'default': 'q62'} },
    "q61_a": { text: "What patterns or activities consistently precede your low energy days?", next: {'default': 'q62'} },
    "q62": { text: "My body often feels heavy or slowed down.", next: {'0': 'q63', '1': 'q63', '2': 'q62_a', '3': 'q62_a', '4': 'q62_a', 'default': 'q63'} },
    "q62_a": { text: "What activities worsen or improve your sensation of heaviness or slowed movement?", next: {'default': 'q63'} },
    "q63": { text: "Small tasks consume more energy than they should.", next: {'0': 'q64', '1': 'q64', '2': 'q63_a', '3': 'q63_a', '4': 'q63_a', 'default': 'q64'} },
    "q63_a": { text: "What specific tasks feel most draining, and when do you notice this increase in effort?", next: {'default': 'q64'} },
    "q64": { text: "Fatigue makes me doubt myself morally instead of practically.", next: {'0': 'q65', '1': 'q65', '2': 'q64_a', '3': 'q64_a', '4': 'q64_a', 'default': 'q65'} },
    "q64_a": { text: "What specific situations trigger moral doubt when you're fatigued?", next: {'default': 'q65'} },
    "q65": { text: "I feel physically deconditioned or weaker than I should.", next: {'0': 'q66', '1': 'q66', '2': 'q65_a', '3': 'q65_a', '4': 'q65_a', 'default': 'q66'} },
    "q65_a": { text: "What changes in activity or lifestyle might have contributed to this deconditioning?", next: {'default': 'q66'} },
    "q66": { text: "My appetite or food intake becomes erratic when I am low.", next: {'0': 'q67', '1': 'q67', '2': 'q66_a', '3': 'q66_a', '4': 'q66_a', 'default': 'q67'} },
    "q66_a": { text: "What triggers or alleviates your appetite changes when you're feeling low?", next: {'default': 'q67'} },
    "q67": { text: "I go too long without eating or drinking enough.", next: {'0': 'q68', '1': 'q68', '2': 'q67_a', '3': 'q67_a', '4': 'q67_a', 'default': 'q68'} },
    "q67_a": { text: "What factors prevent you from eating or drinking regularly throughout the day?", next: {'default': 'q68'} },
    "q68": { text: "My physical state worsens my mood more than I admit.", next: {'0': 'q69', '1': 'q69', '2': 'q68_a', '3': 'q68_a', '4': 'q68_a', 'default': 'q69'} },
    "q68_a": { text: "What specific physical symptoms most frequently correlate with your mood worsening?", next: {'default': 'q69'} },
    "q69": { text: "I feel restless or agitated instead of simply tired.", next: {'0': 'q70', '1': 'q70', '2': 'q69_a', '3': 'q69_a', '4': 'q69_a', 'default': 'q70'} },
    "q69_a": { text: "What specific situations trigger your feelings of restlessness or agitation?", next: {'default': 'q70'} },
    "q70": { text: "I rely on substances, caffeine, nicotine, or other inputs to push through collapse.", next: {'0': 'q71', '1': 'q71', '2': 'q70_a', '3': 'q70_a', '4': 'q70_a', 'default': 'q71'} },
    "q70_a": { text: "What patterns trigger your reliance on substances to overcome feelings of collapse?", next: {'default': 'q71'} },
    "q71": { text: "Physical discomfort or pain is feeding the depressive state.", next: {'0': 'q72', '1': 'q72', '2': 'q71_a', '3': 'q71_a', '4': 'q71_a', 'default': 'q72'} },
    "q71_a": { text: "What specific physical discomforts most intensify your depressive symptoms?", next: {'default': 'q72'} },
    "q72": { text: "I have trouble telling the difference between exhaustion and avoidance.", next: {'0': 'q73', '1': 'q73', '2': 'q72_a', '3': 'q72_a', '4': 'q72_a', 'default': 'q73'} },
    "q72_a": { text: "What situations trigger confusion between exhaustion and avoidance for you?", next: {'default': 'q73'} },
    "q73": { text: "I often wait to feel energized before attempting anything useful.", next: {'0': 'q74', '1': 'q74', '2': 'q73_a', '3': 'q73_a', '4': 'q73_a', 'default': 'q74'} },
    "q73_a": { text: "What factors contribute to your lack of energy before starting tasks?", next: {'default': 'q74'} },
    "q74": { text: "When my body feels bad, the whole day is easier to lose.", next: {'0': 'q75', '1': 'q75', '2': 'q74_a', '3': 'q74_a', '4': 'q74_a', 'default': 'q75'} },
    "q74_a": { text: "What specific physical sensations most often trigger your day becoming unmanageable?", next: {'default': 'q75'} },
    "q75": { text: "Basic body care is inconsistent enough to affect function.", next: {'0': 'q76', '1': 'q76', '2': 'q75_a', '3': 'q75_a', '4': 'q75_a', 'default': 'q76'} },
    "q75_a": { text: "What specific factors prevent you from maintaining consistent basic body care?", next: {'default': 'q76'} },
    "q76": { text: "I avoid things that might actually help because they feel too hard.", next: {'0': 'q77', '1': 'q77', '2': 'q76_a', '3': 'q76_a', '4': 'q76_a', 'default': 'q77'} },
    "q76_a": { text: "What specific obstacles make helpful tasks feel too challenging for you?", next: {'default': 'q77'} },
    "q77": { text: "I delay tasks until they become bigger and more frightening.", next: {'0': 'q78', '1': 'q78', '2': 'q77_a', '3': 'q77_a', '4': 'q77_a', 'default': 'q78'} },
    "q77_a": { text: "What specific thoughts or fears contribute to delaying these tasks?", next: {'default': 'q78'} },
    "q78": { text: "I use scrolling, numbing, or passive distraction to avoid starting.", next: {'0': 'q79', '1': 'q79', '2': 'q78_a', '3': 'q78_a', '4': 'q78_a', 'default': 'q79'} },
    "q78_a": { text: "What specific emotions or tasks trigger your urge to engage in distraction?", next: {'default': 'q79'} },
    "q79": { text: "I cancel, hide, or withdraw more than I want to.", next: {'0': 'q80', '1': 'q80', '2': 'q79_a', '3': 'q79_a', '4': 'q79_a', 'default': 'q80'} },
    "q79_a": { text: "What specific situations trigger your tendency to cancel or withdraw?", next: {'default': 'q80'} },
    "q80": { text: "I wait to feel ready before acting.", next: {'0': 'q81', '1': 'q81', '2': 'q80_a', '3': 'q80_a', '4': 'q80_a', 'default': 'q81'} },
    "q80_a": { text: "What fears or beliefs contribute to needing to feel ready before acting?", next: {'default': 'q81'} },
    "q81": { text: "I start less than I plan.", next: {'0': 'q82', '1': 'q82', '2': 'q81_a', '3': 'q81_a', '4': 'q81_a', 'default': 'q82'} },
    "q81_a": { text: "What specific obstacles prevent you from initiating planned tasks?", next: {'default': 'q82'} },
    "q82": { text: "I follow through less than I intend.", next: {'0': 'q83', '1': 'q83', '2': 'q82_a', '3': 'q82_a', '4': 'q82_a', 'default': 'q83'} },
    "q82_a": { text: "What specific obstacles prevent you from completing tasks as intended?", next: {'default': 'q83'} },
    "q83": { text: "Once I slip, I tend to abandon the whole day.", next: {'0': 'q84', '1': 'q84', '2': 'q83_a', '3': 'q83_a', '4': 'q83_a', 'default': 'q84'} },
    "q83_a": { text: "What specific triggers typically cause you to slip and abandon the day?", next: {'default': 'q84'} },
    "q84": { text: "I turn one mistake into a reason to stop trying.", next: {'0': 'q85', '1': 'q85', '2': 'q84_a', '3': 'q84_a', '4': 'q84_a', 'default': 'q85'} },
    "q84_a": { text: "What past experiences contribute to stopping efforts after a mistake?", next: {'default': 'q85'} },
    "q85": { text: "My routines disappear when mood drops.", next: {'0': 'q86', '1': 'q86', '2': 'q85_a', '3': 'q85_a', '4': 'q85_a', 'default': 'q86'} },
    "q85_a": { text: "What specific routines are hardest to maintain when your mood drops?", next: {'default': 'q86'} },
    "q86": { text: "I can think clearly about the plan but not run it consistently.", next: {'0': 'q87', '1': 'q87', '2': 'q86_a', '3': 'q86_a', '4': 'q86_a', 'default': 'q87'} },
    "q86_a": { text: "What specific obstacles prevent you from consistently executing your plans?", next: {'default': 'q87'} },
    "q87": { text: "I choose short-term relief over longer-term function.", next: {'0': 'q88', '1': 'q88', '2': 'q87_a', '3': 'q87_a', '4': 'q87_a', 'default': 'q88'} },
    "q87_a": { text: "What specific situations trigger choosing short-term relief over long-term function?", next: {'default': 'q88'} },
    "q88": { text: "I have trouble scaling the day to my actual energy.", next: {'0': 'q89', '1': 'q89', '2': 'q88_a', '3': 'q88_a', '4': 'q88_a', 'default': 'q89'} },
    "q88_a": { text: "What specific factors prevent you from adjusting your activities to your energy levels?", next: {'default': 'q89'} },
    "q89": { text: "I overreach on better days and pay for it later.", next: {'0': 'q90', '1': 'q90', '2': 'q89_a', '3': 'q89_a', '4': 'q89_a', 'default': 'q90'} },
    "q89_a": { text: "What specific activities do you tend to overcommit to on better days?", next: {'default': 'q90'} },
    "q90": { text: "My life is more passive than I want it to be.", next: {'0': 'q91', '1': 'q91', '2': 'q90_a', '3': 'q90_a', '4': 'q90_a', 'default': 'q91'} },
    "q90_a": { text: "What barriers prevent you from taking more active control in your life?", next: {'default': 'q91'} },
    "q91": { text: "My room, home, or daily environment makes functioning harder.", next: {'0': 'q92', '1': 'q92', '2': 'q91_a', '3': 'q91_a', '4': 'q91_a', 'default': 'q92'} },
    "q91_a": { text: "What specific environmental factors are most disruptive to your daily functioning?", next: {'default': 'q92'} },
    "q92": { text: "Clutter, mess, or friction drains more energy than I admit.", next: {'0': 'q93', '1': 'q93', '2': 'q92_a', '3': 'q92_a', '4': 'q92_a', 'default': 'q93'} },
    "q92_a": { text: "What specific situations trigger the highest energy drain from clutter or mess?", next: {'default': 'q93'} },
    "q93": { text: "Bills, paperwork, appointments, or admin tasks are slipping.", next: {'0': 'q94', '1': 'q94', '2': 'q93_a', '3': 'q93_a', '4': 'q93_a', 'default': 'q94'} },
    "q93_a": { text: "What specific obstacles prevent you from managing bills and paperwork effectively?", next: {'default': 'q94'} },
    "q94": { text: "I lose traction because needed items are not where I can find them.", next: {'0': 'q95', '1': 'q95', '2': 'q94_a', '3': 'q94_a', '4': 'q94_a', 'default': 'q95'} },
    "q94_a": { text: "What specific situations or locations do you most frequently misplace important items?", next: {'default': 'q95'} },
    "q95": { text: "My environment makes good habits harder to run.", next: {'0': 'q96', '1': 'q96', '2': 'q95_a', '3': 'q95_a', '4': 'q95_a', 'default': 'q96'} },
    "q95_a": { text: "What specific environmental factors make it difficult to maintain good habits?", next: {'default': 'q96'} },
    "q96": { text: "I am falling behind on tasks that keep life stable.", next: {'0': 'q97', '1': 'q97', '2': 'q96_a', '3': 'q96_a', '4': 'q96_a', 'default': 'q97'} },
    "q96_a": { text: "What specific obstacles are preventing you from completing essential daily tasks?", next: {'default': 'q97'} },
    "q97": { text: "Work or practical responsibilities feel increasingly threatening.", next: {'0': 'q98', '1': 'q98', '2': 'q97_a', '3': 'q97_a', '4': 'q97_a', 'default': 'q98'} },
    "q97_a": { text: "What specific work tasks contribute most to your sense of threat or anxiety?", next: {'default': 'q98'} },
    "q98": { text: "My day lacks enough structure to protect me from drift.", next: {'0': 'q99', '1': 'q99', '2': 'q98_a', '3': 'q98_a', '4': 'q98_a', 'default': 'q99'} },
    "q98_a": { text: "What factors prevent you from establishing a consistent daily routine?", next: {'default': 'q99'} },
    "q99": { text: "I do better with external structure than without it.", next: {'0': 'q100', '1': 'q100', '2': 'q99_a', '3': 'q99_a', '4': 'q99_a', 'default': 'q100'} },
    "q99_a": { text: "What specific structures help improve your daily functioning and decision-making?", next: {'default': 'q100'} },
    "q100": { text: "When external structure disappears, I unravel quickly.", next: {'0': 'q101', '1': 'q101', '2': 'q100_a', '3': 'q100_a', '4': 'q100_a', 'default': 'q101'} },
    "q100_a": { text: "What specific situations trigger this loss of structure and subsequent unraveling?", next: {'default': 'q101'} },
    "q101": { text: "I spend too much time reacting instead of running a plan.", next: {'0': 'q102', '1': 'q102', '2': 'q101_a', '3': 'q101_a', '4': 'q101_a', 'default': 'q102'} },
    "q101_a": { text: "What factors typically trigger your reactive responses over planned actions?", next: {'default': 'q102'} },
    "q102": { text: "My current systems for tracking or reminders are too weak.", next: {'0': 'q103', '1': 'q103', '2': 'q102_a', '3': 'q102_a', '4': 'q102_a', 'default': 'q103'} },
    "q102_a": { text: "What challenges prevent your tracking or reminder systems from being effective?", next: {'default': 'q103'} },
    "q103": { text: "I am not using written structure as much as I need.", next: {'0': 'q104', '1': 'q104', '2': 'q103_a', '3': 'q103_a', '4': 'q103_a', 'default': 'q104'} },
    "q103_a": { text: "What barriers prevent you from utilizing written structure effectively in daily tasks?", next: {'default': 'q104'} },
    "q104": { text: "My environment becomes an accomplice to collapse.", next: {'0': 'q105', '1': 'q105', '2': 'q104_a', '3': 'q104_a', '4': 'q104_a', 'default': 'q105'} },
    "q104_a": { text: "What environmental factors contribute most to your sense of collapse?", next: {'default': 'q105'} },
    "q105": { text: "Practical life friction is a major maintaining factor right now.", next: {'0': 'q106', '1': 'q106', '2': 'q105_a', '3': 'q105_a', '4': 'q105_a', 'default': 'q106'} },
    "q105_a": { text: "What specific practical life obstacles are most contributing to your current challenges?", next: {'default': 'q106'} },
    "q106": { text: "I withdraw from people when I am low.", next: {'0': 'q107', '1': 'q107', '2': 'q106_a', '3': 'q106_a', '4': 'q106_a', 'default': 'q107'} },
    "q106_a": { text: "What specific situations trigger your withdrawal from others when feeling low?", next: {'default': 'q107'} },
    "q107": { text: "I feel like a burden to others.", next: {'0': 'q108', '1': 'q108', '2': 'q107_a', '3': 'q107_a', '4': 'q107_a', 'default': 'q108'} },
    "q107_a": { text: "What specific situations make you feel most like a burden to others?", next: {'default': 'q108'} },
    "q108": { text: "I expect misunderstanding or rejection more than support.", next: {'0': 'q109', '1': 'q109', '2': 'q108_a', '3': 'q108_a', '4': 'q108_a', 'default': 'q109'} },
    "q108_a": { text: "What past experiences have led you to expect misunderstanding or rejection?", next: {'default': 'q109'} },
    "q109": { text: "I communicate less clearly or less often than I want to.", next: {'0': 'q110', '1': 'q110', '2': 'q109_a', '3': 'q109_a', '4': 'q109_a', 'default': 'q110'} },
    "q109_a": { text: "What specific barriers prevent you from communicating as clearly or as often as desired?", next: {'default': 'q110'} },
    "q110": { text: "Relationships feel harder to maintain than they should.", next: {'0': 'q111', '1': 'q111', '2': 'q110_a', '3': 'q110_a', '4': 'q110_a', 'default': 'q111'} },
    "q110_a": { text: "What specific challenges do you encounter when trying to maintain relationships?", next: {'default': 'q111'} },
    "q111": { text: "Loneliness is feeding the depressive state.", next: {'0': 'q112', '1': 'q112', '2': 'q111_a', '3': 'q111_a', '4': 'q111_a', 'default': 'q112'} },
    "q111_a": { text: "What specific situations or factors contribute most to your feelings of loneliness?", next: {'default': 'q112'} },
    "q112": { text: "Shame makes me harder to reach.", next: {'0': 'q113', '1': 'q113', '2': 'q112_a', '3': 'q112_a', '4': 'q112_a', 'default': 'q113'} },
    "q112_a": { text: "What specific situations trigger the shame that hinders your ability to connect?", next: {'default': 'q113'} },
    "q113": { text: "I have become less expressive or less responsive.", next: {'0': 'q114', '1': 'q114', '2': 'q113_a', '3': 'q113_a', '4': 'q113_a', 'default': 'q114'} },
    "q113_a": { text: "What specific situations trigger your decreased expressiveness or responsiveness?", next: {'default': 'q114'} },
    "q114": { text: "I lose contact with parts of my identity outside depression.", next: {'0': 'q115', '1': 'q115', '2': 'q114_a', '3': 'q114_a', '4': 'q114_a', 'default': 'q115'} },
    "q114_a": { text: "What aspects of your identity feel most diminished during depressive episodes?", next: {'default': 'q115'} },
    "q115": { text: "I feel smaller, narrower, or less like myself than before.", next: {'0': 'q116', '1': 'q116', '2': 'q115_a', '3': 'q115_a', '4': 'q115_a', 'default': 'q116'} },
    "q115_a": { text: "What recent events or changes might be contributing to this diminished self-perception?", next: {'default': 'q116'} },
    "q116": { text: "Social effort feels expensive even when I want connection.", next: {'0': 'q117', '1': 'q117', '2': 'q116_a', '3': 'q116_a', '4': 'q116_a', 'default': 'q117'} },
    "q116_a": { text: "What specific situations make social interaction feel most draining for you?", next: {'default': 'q117'} },
    "q117": { text: "I avoid people because I do not want to be seen like this.", next: {'0': 'q118', '1': 'q118', '2': 'q117_a', '3': 'q117_a', '4': 'q117_a', 'default': 'q118'} },
    "q117_a": { text: "What specific situations trigger your need to avoid people?", next: {'default': 'q118'} },
    "q118": { text: "When others respond badly, it confirms my worst beliefs fast.", next: {'0': 'q119', '1': 'q119', '2': 'q118_a', '3': 'q118_a', '4': 'q118_a', 'default': 'q119'} },
    "q118_a": { text: "What past experiences reinforce your belief when others respond badly to you?", next: {'default': 'q119'} },
    "q119": { text: "I need more low-pressure human contact than I currently get.", next: {'0': 'q120', '1': 'q120', '2': 'q119_a', '3': 'q119_a', '4': 'q119_a', 'default': 'q120'} },
    "q119_a": { text: "What barriers or circumstances limit your ability to have low-pressure social interactions?", next: {'default': 'q120'} },
    "q120": { text: "Depression has started to fuse with my sense of who I am.", next: {'0': 'q121', '1': 'q121', '2': 'q120_a', '3': 'q120_a', '4': 'q120_a', 'default': 'q121'} },
    "q120_a": { text: "How has this fusion with depression affected your daily decision-making processes?", next: {'default': 'q121'} },
    "q121": { text: "I have had depressive periods before this current one.", next: {'0': 'q122', '1': 'q122', '2': 'q121_a', '3': 'q121_a', '4': 'q121_a', 'default': 'q122'} },
    "q121_a": { text: "What triggers have you identified that precede your depressive periods?", next: {'default': 'q122'} },
    "q122": { text: "This current state feels chronic, recurrent, or stubborn.", next: {'0': 'q123', '1': 'q123', '2': 'q122_a', '3': 'q122_a', '4': 'q122_a', 'default': 'q123'} },
    "q122_a": { text: "What recurring triggers or stressors have you identified that exacerbate this state?", next: {'default': 'q123'} },
    "q123": { text: "I suspect there are contributing factors beyond just mood.", next: {'0': 'q124', '1': 'q124', '2': 'q123_a', '3': 'q123_a', '4': 'q123_a', 'default': 'q124'} },
    "q123_a": { text: "What specific factors beyond mood do you believe are influencing your situation?", next: {'default': 'q124'} },
    "q124": { text: "Physical health issues may be worsening the depression picture.", next: {'0': 'q125', '1': 'q125', '2': 'q124_a', '3': 'q124_a', '4': 'q124_a', 'default': 'q125'} },
    "q124_a": { text: "What specific physical health issues are contributing to your worsening depression symptoms?", next: {'default': 'q125'} },
    "q125": { text: "Substances or medication side effects may be part of the picture.", next: {'0': 'q126', '1': 'q126', '2': 'q125_a', '3': 'q125_a', '4': 'q125_a', 'default': 'q126'} },
    "q125_a": { text: "Which specific substances or medications are affecting your daily functioning the most?", next: {'default': 'q126'} },
    "q126": { text: "My current medication strategy, if any, is not fully optimized.", next: {'0': 'q127', '1': 'q127', '2': 'q126_a', '3': 'q126_a', '4': 'q126_a', 'default': 'q127'} },
    "q126_a": { text: "What specific issues have you noticed with your current medication strategy?", next: {'default': 'q127'} },
    "q127": { text: "Side effects or treatment tradeoffs are affecting function.", next: {'0': 'q128', '1': 'q128', '2': 'q127_a', '3': 'q127_a', '4': 'q127_a', 'default': 'q128'} },
    "q127_a": { text: "Which specific side effects are most disruptive to your daily activities?", next: {'default': 'q128'} },
    "q128": { text: "I have trouble judging treatment by concrete outcomes instead of ideology or mood memory.", next: {'0': 'q129', '1': 'q129', '2': 'q128_a', '3': 'q128_a', '4': 'q128_a', 'default': 'q129'} },
    "q128_a": { text: "What specific patterns or past experiences influence your treatment judgments the most?", next: {'default': 'q129'} },
    "q129": { text: "I do not track changes in sleep, energy, mood, and side effects clearly enough.", next: {'0': 'q130', '1': 'q130', '2': 'q129_a', '3': 'q129_a', '4': 'q129_a', 'default': 'q130'} },
    "q129_a": { text: "What barriers prevent you from consistently tracking sleep, energy, mood, and side effects?", next: {'default': 'q130'} },
    "q130": { text: "Access, cost, time, or logistics make treatment harder.", next: {'0': 'q131', '1': 'q131', '2': 'q130_a', '3': 'q130_a', '4': 'q130_a', 'default': 'q131'} },
    "q130_a": { text: "Which specific barrier\u2014access, cost, time, or logistics\u2014affects your treatment the most?", next: {'default': 'q131'} },
    "q131": { text: "I have trouble staying consistent with helpful treatment inputs.", next: {'0': 'q132', '1': 'q132', '2': 'q131_a', '3': 'q131_a', '4': 'q131_a', 'default': 'q132'} },
    "q131_a": { text: "What obstacles prevent you from consistently engaging with your treatment plan?", next: {'default': 'q132'} },
    "q132": { text: "I need a plan that fits real life better, not a theoretically perfect one.", next: {'0': 'q133', '1': 'q133', '2': 'q132_a', '3': 'q132_a', '4': 'q132_a', 'default': 'q133'} },
    "q132_a": { text: "What specific obstacles prevent you from following your current plan effectively?", next: {'default': 'q133'} },
    "q133": { text: "My depression may be complicated by anxiety, trauma, pain, burnout, or heavy stress.", next: {'0': 'q134', '1': 'q134', '2': 'q133_a', '3': 'q133_a', '4': 'q133_a', 'default': 'q134'} },
    "q133_a": { text: "Which factor most frequently triggers or intensifies your depressive episodes?", next: {'default': 'q134'} },
    "q134": { text: "I need better collaborative decision-making around treatment than I currently have.", next: {'0': 'q135', '1': 'q135', '2': 'q134_a', '3': 'q134_a', '4': 'q134_a', 'default': 'q135'} },
    "q134_a": { text: "What specific barriers are hindering effective collaboration in your treatment decisions?", next: {'default': 'q135'} },
    "q135": { text: "My current approach is too fragmented to be reliable.", next: {'0': 'q136', '1': 'q136', '2': 'q135_a', '3': 'q135_a', '4': 'q135_a', 'default': 'q136'} },
    "q135_a": { text: "What factors contribute to the fragmentation in your current approach?", next: {'default': 'q136'} },
    "q136": { text: "It is hard to believe effort will lead to improvement.", next: {'0': 'q137', '1': 'q137', '2': 'q136_a', '3': 'q136_a', '4': 'q136_a', 'default': 'q137'} },
    "q136_a": { text: "What past experiences have reinforced your belief that effort doesn't lead to improvement?", next: {'default': 'q137'} },
    "q137": { text: "I have trouble noticing small gains once they happen.", next: {'0': 'q138', '1': 'q138', '2': 'q137_a', '3': 'q137_a', '4': 'q137_a', 'default': 'q138'} },
    "q137_a": { text: "What factors prevent you from recognizing and acknowledging small improvements in your progress?", next: {'default': 'q138'} },
    "q138": { text: "I discount small corrective actions as meaningless.", next: {'0': 'q139', '1': 'q139', '2': 'q138_a', '3': 'q138_a', '4': 'q138_a', 'default': 'q139'} },
    "q138_a": { text: "What past experiences led you to view small actions as insignificant?", next: {'default': 'q139'} },
    "q139": { text: "I need visible evidence that inputs can change the state.", next: {'0': 'q140', '1': 'q140', '2': 'q139_a', '3': 'q139_a', '4': 'q139_a', 'default': 'q140'} },
    "q139_a": { text: "What specific situations trigger your need for visible evidence of change?", next: {'default': 'q140'} },
    "q140": { text: "I do better when expectations are realistic and scaled.", next: {'0': 'q141', '1': 'q141', '2': 'q140_a', '3': 'q140_a', '4': 'q140_a', 'default': 'q141'} },
    "q140_a": { text: "How do unrealistic expectations typically impact your ability to meet goals?", next: {'default': 'q141'} },
    "q141": { text: "I need a minimum viable day plan for bad days.", next: {'0': 'q142', '1': 'q142', '2': 'q141_a', '3': 'q141_a', '4': 'q141_a', 'default': 'q142'} },
    "q141_a": { text: "What specific obstacles prevent you from achieving a minimum viable day plan?", next: {'default': 'q142'} },
    "q142": { text: "I need a rescue plan for collapse days.", next: {'0': 'q143', '1': 'q143', '2': 'q142_a', '3': 'q142_a', '4': 'q142_a', 'default': 'q143'} },
    "q142_a": { text: "What triggers your collapse days, and how do you currently manage them?", next: {'default': 'q143'} },
    "q143": { text: "I need clearer priorities about which anchors matter most first.", next: {'0': 'q144', '1': 'q144', '2': 'q143_a', '3': 'q143_a', '4': 'q143_a', 'default': 'q144'} },
    "q143_a": { text: "What factors make it difficult for you to prioritize these anchors effectively?", next: {'default': 'q144'} },
    "q144": { text: "I need a plan that protects continuity rather than perfection.", next: {'0': 'q145', '1': 'q145', '2': 'q144_a', '3': 'q144_a', '4': 'q144_a', 'default': 'q145'} },
    "q144_a": { text: "What obstacles prevent you from prioritizing continuity over perfection in your plans?", next: {'default': 'q145'} },
    "q145": { text: "I need a stronger sense of what would count as real progress.", next: {'0': 'q146', '1': 'q146', '2': 'q145_a', '3': 'q145_a', '4': 'q145_a', 'default': 'q146'} },
    "q145_a": { text: "What specific obstacles do you perceive are hindering your sense of progress?", next: {'default': 'q146'} },
    "q146": { text: "I need more repetition and less heroic overcorrection.", next: {'0': 'q147', '1': 'q147', '2': 'q146_a', '3': 'q146_a', '4': 'q146_a', 'default': 'q147'} },
    "q146_a": { text: "What specific situations trigger your need for repetition and avoidance of overcorrection?", next: {'default': 'q147'} },
    "q147": { text: "I need a better way to identify my main constraints.", next: {'0': 'q148', '1': 'q148', '2': 'q147_a', '3': 'q147_a', '4': 'q147_a', 'default': 'q148'} },
    "q147_a": { text: "What specific constraints do you feel are hindering your progress the most?", next: {'default': 'q148'} },
    "q148": { text: "I need the plan to meet me at my actual capacity, not an ideal version of me.", next: {'0': 'q149', '1': 'q149', '2': 'q148_a', '3': 'q148_a', '4': 'q148_a', 'default': 'q149'} },
    "q148_a": { text: "What factors prevent you from aligning your plans with your true capacity?", next: {'default': 'q149'} },
    "q149": { text: "It is hard to hold onto the idea that any part of this can still change.", next: {'0': 'q150', '1': 'q150', '2': 'q149_a', '3': 'q149_a', '4': 'q149_a', 'default': 'q150'} },
    "q149_a": { text: "What specific experiences contribute to your belief that change is impossible?", next: {'default': 'q150'} },
    "q150": { text: "I struggle to keep testing small repeated changes when immediate payoff is low.", next: {'0': 'done', '1': 'done', '2': 'q150_a', '3': 'q150_a', '4': 'q150_a', 'default': 'done'} },
    "q150_a": { text: "What obstacles prevent sustained effort when rewards are not immediately apparent?", next: {'default': 'done'} },
};
if (typeof module !== 'undefined') module.exports = { COMPANION_QUESTION_TREE };
